Repository roseline124/dreambody, pull requests merged in 2020-06, with the labels that each got.

#5 Add github action flow
  .github/workflows/dart.yml
Labels: size/S

#1 [WIP] Add question screens
  android/.project
  android/.settings/org.eclipse.buildship.core.prefs
  lib/main.dart
  lib/screens/QuestionScreen/questionFour.dart
  lib/screens/QuestionScreen/questionOne.dart
  lib/screens/QuestionScreen/questionTwo.dart
  lib/screens/homeScreen/homeScreen.dart
  lib/widgets/button.dart
  lib/widgets/selectForm.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: WIP, size/XL

#6 [Week1] add question screens
  lib/main.dart
  lib/screens/QuestionScreen/questionFive.dart
  lib/screens/QuestionScreen/questionFour.dart
  lib/screens/QuestionScreen/questionOne.dart
  lib/screens/QuestionScreen/questionSix.dart
  lib/screens/QuestionScreen/questionThree/imageButton.dart
  lib/screens/QuestionScreen/questionThree/questionThree.dart
  lib/screens/QuestionScreen/questionTwo.dart
  lib/widgets/datePicker.dart
  lib/widgets/hexColor.dart
  lib/widgets/selectForm.dart
  pubspec.lock
  pubspec.yaml
  static/images/femaleUser_128.png
  static/images/maleUser_128.png
Labels: size/XL

#8 Add type selection screen
  lib/screens/homeScreen/homeScreen.dart
  lib/screens/signInScreen/signIn.dart
  lib/screens/typeSelectionScreen/typeButton.dart
  lib/screens/typeSelectionScreen/typeSelection.dart
Labels: size/L

#9 Fix type button style
  lib/screens/homeScreen/homeScreen.dart
  lib/screens/typeSelectionScreen/typeButton.dart
Labels: size/S

#13 [Week2] Add water dashboard
  lib/main.dart
  lib/screens/dashboardScreen/waterDashboard.dart
  lib/screens/dashboardScreen/waterWave.dart
  lib/screens/questionScreen/questionSix.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#14 Add dash board
  .gitignore
  .vscode/launch.json
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/screens/dashboardScreen/calorieCounter.dart
  lib/screens/dashboardScreen/nutrientsCounter.dart
  lib/screens/dashboardScreen/perDayDashboard.dart
  lib/widgets/pie_chart.dart
  pubspec.yaml
Labels: size/L

#12 Add login feature
  README.md
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/config.dart
  lib/main.dart
  lib/screens/homeScreen/homeScreen.dart
  lib/screens/signInScreen/googleSignIn.dart
  lib/screens/signInScreen/signIn.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L
